name: MercuryServer
description: Dart Server for Flutter.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0
  async: ^2.2.0
  grpc: ^2.1.2
  protobuf: ^1.0.1
  process_run: ^0.10.11+1
